alias ll='ls -hla'
alias reload!='. ~/.profile'
alias binstubs='export PATH=./bin:${PATH%:./bin}'
alias gif-optimize-64='gifsicle --colors=64 --optimize=3 '
alias gif-optimize-32='gifsicle --colors=32 --optimize=3'
alias cask='brew cask'
alias g='git'
